# Generated by Django 4.2.4 on 2023-08-17 07:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, help_text='Введите название ингредиента, поле обязательное для заполнения', max_length=200, verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(blank=True, help_text='Введите единицу измерения для ингредиента, поле обязательное для заполнения', max_length=200, verbose_name='Единица измерения для ингредиента')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='cats/images/')),
                ('name', models.CharField(blank=True, help_text='Введите название рецепта, поле обязательное для заполнения', max_length=200, verbose_name='Название рецепта')),
                ('text', models.TextField(help_text='Введите описание рецепта,поле обязательное для заполнения', verbose_name='Описание рецепта')),
                ('cooking_time', models.IntegerField(blank=True, help_text='Введите время приготовления рецепта в минутах,можно ввести только целое число, поле обязательное для заполнения', validators=[django.core.validators.MinValueValidator(1, 'Можно ввести только целое, положительное число')], verbose_name='Время приготовления')),
                ('pub_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тег для рецепта, поле обязательное для заполнения, поле должно быть уникальным', max_length=200, unique=True, verbose_name='Название тега')),
                ('color', models.CharField(max_length=7, validators=[utils.validators.hex_name_color_validator])),
                ('slug', models.SlugField(help_text='Введите тег рецепта, поле обязательное для заполнения, поле должно быть уникальным', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_field', message='Неправильный формат поляПоле может содержать только буквы,цифры и следующие символы: @ . + -', regex='^[\\w.@+-]+$')], verbose_name='Slug тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodgram.recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodgram.tag')),
            ],
            options={
                'verbose_name': 'Тег рецепта',
                'verbose_name_plural': 'Тег рецептов',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, help_text='Введите количество ингредиента,можно ввести только целое число, поле обязательное для заполнения', validators=[django.core.validators.MinValueValidator(1, 'Можно ввести только целое, положительное число')], verbose_name='Количество ингредиента')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodgram.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodgram.recipe')),
            ],
            options={
                'verbose_name': 'Ингредиент рецепта',
                'verbose_name_plural': 'Ингредиенты рецепта',
            },
        ),
    ]
